FROM jenkins/jenkins:lts-jdk17
user root
RUN apt-get update
RUN apt-get install wget software-properties-common -y
RUN apt-get install -y python3
RUN apt-get install -y apt-utils
RUN apt-get install -y python3-venv
