pipeline {
    agent any

    environment {
        VENV_PATH = '/root/translator/venv'
    }

    stages {
        stage('Cleanup') {
            steps {
                sh 'rm -rf /root/*' // Удаление всех предыдущих файлов
            }
        }

        stage('Checkout') {
            steps {
                git 'https://github.com/nocsland/other-projects.git'
                sh 'ls -al /root/translator/'
            }
        }

        stage('Install pip') {
            steps {
                sh 'apt update && apt install -y python3-pip python3-venv'
            }
        }

        stage('Install dependencies') {
            steps {
                script {
                    dir('/root/translator/') {
                        sh 'python3 -m venv venv'
                        sh 'chmod +x venv/bin/activate'
                        sh './venv/bin/activate'
                        sh 'ls /root/translator/'
                        sh 'venv/bin/pip3 install -r /root/translator/requirements.txt'
                    }
                }
            }
        }

        stage('Build Docker image') {
            steps {
                script {
                    dir('/root/translator/') {
                        sh 'docker build -t translator-container .'
                    }
                }
            }
        }
    }
}
